"""Delete pre-instrumentation flags for pat_test_01.

Reason: the demo system should show only flags from the current production
pipeline (post-NER-fix, post-audit-hashing). Leaving 167 historical flags
(many with the postcode-collision garbage from before yesterday's NER fix)
makes the briefing agent and flags page show noise.

Safety:
  - Restricted to flags WITHOUT provenance_hash (the historical set)
  - Restricted to patient_id = pat_test_01
  - Counts before + after to confirm intent matches reality
  - The forced re-process script run immediately after will populate
    new flags with hashes from the clean pipeline.

Out of scope: contradictions, timeline events. Those are regenerated by
the orchestrator anyway during the re-process; their stale rows will get
naturally replaced.
"""
import os
import snowflake.connector
from dotenv import load_dotenv

load_dotenv()

PATIENT = "pat_test_01"

conn = snowflake.connector.connect(
    account=os.environ["SNOWFLAKE_ACCOUNT"],
    user=os.environ["SNOWFLAKE_USER"],
    password=os.environ["SNOWFLAKE_PASSWORD"],
    database="clinical_db",
    warehouse="clinical_wh",
    role=os.environ["SNOWFLAKE_ROLE"],
)
try:
    cur = conn.cursor()

    cur.execute(
        "SELECT COUNT(*), COUNT(provenance_hash) "
        "FROM clinical_db.core.flag WHERE patient_id = %s",
        (PATIENT,),
    )
    total_before, hashed_before = cur.fetchone()
    print(f"Before: {total_before} total, {hashed_before} hashed, "
          f"{total_before - hashed_before} unhashed (will be deleted)")

    cur.execute(
        "DELETE FROM clinical_db.core.flag "
        "WHERE patient_id = %s AND provenance_hash IS NULL",
        (PATIENT,),
    )
    deleted = cur.rowcount
    conn.commit()
    print(f"Deleted: {deleted} unhashed flags")

    cur.execute(
        "SELECT COUNT(*), COUNT(provenance_hash) "
        "FROM clinical_db.core.flag WHERE patient_id = %s",
        (PATIENT,),
    )
    total_after, hashed_after = cur.fetchone()
    print(f"After:  {total_after} total, {hashed_after} hashed, "
          f"{total_after - hashed_after} unhashed")

    if total_after - hashed_after != 0:
        print("[WARN] some unhashed flags remain - investigate")
    else:
        print("[OK] all remaining flags are hashed")
finally:
    conn.close()